name: thevoices
favicon: null
layout_spectrum: 0.74324
typography_spectrum: 0.5511706210672855
title: Voices
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 1
  lightness: 0.4013010459020734
  saturation: 0.06161120953038335
  rhythmicContrast: 0.9570212282706052
purpose: []
